language: node_js

node_js:
  - "6"

env:
  global:
    - NODE_ENV=test
    - MONGODB_URI=mongodb://localhost/service

before_script:
  - "cd server"
  - "npm install"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - npm run coveralls

after_success:
  - bash <(curl -s https://codecov.io/bash)

services: mongodb
