# Reverse Proxy
nginx:
    build: ./nginx
    links:
        - microservice1:microservice1
        - microservice2:microservice2
        - microservice3:microservice3
    ports:
        - "80:80"

# NodeJS RESTful API Microservice
microservice1:
    build: ./server/dist
    links:
        - mongo:mongo
    ports:
        - "9001:9000"
    environment:
        NODE_ENV: production
        MONGODB_URI: mongodb://mongo/service
        IP: 0.0.0.0
        PORT: 9000
microservice2:
    build: ./server/dist
    links:
        - mongo:mongo
    ports:
        - "9002:9000"
    environment:
        NODE_ENV: production
        MONGODB_URI: mongodb://mongo/service
        IP: 0.0.0.0
        PORT: 9000
microservice3:
    build: ./server/dist
    links:
        - mongo:mongo
    ports:
        - "9003:9000"
    environment:
        NODE_ENV: production
        MONGODB_URI: mongodb://mongo/service
        IP: 0.0.0.0
        PORT: 9000

# MongoDB
mongo:
    image: mongo
    ports:
        - "27017:27017"
